import { ProductCard } from "@/components/product-card"

// Mock product data
const products = [
  {
    id: "1",
    title: "Bamboo Fiber Water Bottle",
    description: "Eco-friendly water bottle made from sustainable bamboo fiber",
    price: 2099,
    category: "Home & Garden",
    image: "/bamboo-fiber-water-bottle-eco-friendly.jpg",
    seller: "EcoLife Store",
    rating: 4.8,
    reviews: 124,
    isVerified: true,
  },
  {
    id: "2",
    title: "Organic Cotton T-Shirt",
    description: "Soft, comfortable t-shirt made from 100% organic cotton",
    price: 2650,
    category: "Fashion",
    image: "/organic-cotton-t-shirt-sustainable-fashion.jpg",
    seller: "Green Threads",
    rating: 4.6,
    reviews: 89,
    isVerified: true,
  },
  {
    id: "3",
    title: "Solar Power Bank",
    description: "Portable solar-powered charger for all your devices",
    price: 3799,
    category: "Electronics",
    image: "/solar-power-bank-portable-charger.jpg",
    seller: "SolarTech",
    rating: 4.7,
    reviews: 203,
    isVerified: true,
  },
  {
    id: "4",
    title: "Reusable Food Wraps",
    description: "Beeswax food wraps - plastic-free food storage solution",
    price: 1549,
    category: "Home & Garden",
    image: "/beeswax-food-wraps-reusable-eco-friendly.jpg",
    seller: "Zero Waste Co",
    rating: 4.9,
    reviews: 156,
    isVerified: true,
  },
  {
    id: "5",
    title: "Natural Skincare Set",
    description: "Complete skincare routine with organic ingredients",
    price: 5599,
    category: "Beauty & Personal Care",
    image: "/natural-organic-skincare-products-set.jpg",
    seller: "Pure Beauty",
    rating: 4.5,
    reviews: 78,
    isVerified: true,
  },
  {
    id: "6",
    title: "Recycled Yoga Mat",
    description: "High-quality yoga mat made from recycled materials",
    price: 3299,
    category: "Sports & Outdoors",
    image: "/recycled-yoga-mat-eco-friendly-exercise.jpg",
    seller: "Mindful Movement",
    rating: 4.8,
    reviews: 92,
    isVerified: true,
  },
  // Additional Home & Garden products
  {
    id: "7",
    title: "Compost Bin Set",
    description: "Complete composting system for kitchen and garden waste",
    price: 4299,
    category: "Home & Garden",
    image: "/compost-bin-kitchen-garden-organic-waste.jpg",
    seller: "Garden Green",
    rating: 4.7,
    reviews: 167,
    isVerified: true,
  },
  {
    id: "8",
    title: "LED Plant Grow Light",
    description: "Energy-efficient LED grow light for indoor plants",
    price: 2899,
    category: "Home & Garden",
    image: "/led-plant-grow-light-indoor-gardening.jpg",
    seller: "Indoor Gardens",
    rating: 4.6,
    reviews: 134,
    isVerified: true,
  },
  {
    id: "9",
    title: "Bamboo Kitchen Utensil Set",
    description: "Complete set of bamboo cooking utensils - plastic-free kitchen",
    price: 1899,
    category: "Home & Garden",
    image: "/bamboo-kitchen-utensils-eco-friendly-cooking.jpg",
    seller: "EcoKitchen",
    rating: 4.8,
    reviews: 245,
    isVerified: true,
  },
  // Additional Fashion products
  {
    id: "10",
    title: "Hemp Canvas Backpack",
    description: "Durable backpack made from sustainable hemp fiber",
    price: 3499,
    category: "Fashion",
    image: "/hemp-canvas-backpack-sustainable-fashion.jpg",
    seller: "Green Threads",
    rating: 4.7,
    reviews: 112,
    isVerified: true,
  },
  {
    id: "11",
    title: "Recycled Denim Jacket",
    description: "Stylish jacket crafted from recycled denim materials",
    price: 4599,
    category: "Fashion",
    image: "/recycled-denim-jacket-sustainable-fashion.jpg",
    seller: "Upcycle Fashion",
    rating: 4.5,
    reviews: 87,
    isVerified: true,
  },
  {
    id: "12",
    title: "Organic Cotton Socks Set",
    description: "Comfortable 5-pack of organic cotton socks",
    price: 1299,
    category: "Fashion",
    image: "/organic-cotton-socks-sustainable-clothing.jpg",
    seller: "Comfort Wear",
    rating: 4.6,
    reviews: 198,
    isVerified: true,
  },
  // Additional Electronics products
  {
    id: "13",
    title: "Bamboo Wireless Speaker",
    description: "Bluetooth speaker with natural bamboo housing",
    price: 5299,
    category: "Electronics",
    image: "/bamboo-wireless-speaker-bluetooth-natural.jpg",
    seller: "EcoSound",
    rating: 4.8,
    reviews: 156,
    isVerified: true,
  },
  {
    id: "14",
    title: "Solar Garden Lights",
    description: "Set of 6 solar-powered LED garden pathway lights",
    price: 2799,
    category: "Electronics",
    image: "/solar-garden-lights-led-pathway-outdoor.jpg",
    seller: "SolarTech",
    rating: 4.7,
    reviews: 289,
    isVerified: true,
  },
  {
    id: "15",
    title: "Energy Monitor Device",
    description: "Smart device to track and reduce home energy consumption",
    price: 6799,
    category: "Electronics",
    image: "/energy-monitor-smart-home-device-efficiency.jpg",
    seller: "SmartEco",
    rating: 4.6,
    reviews: 143,
    isVerified: true,
  },
  // Additional Beauty & Personal Care products
  {
    id: "16",
    title: "Bamboo Toothbrush Set",
    description: "Pack of 4 biodegradable bamboo toothbrushes",
    price: 899,
    category: "Beauty & Personal Care",
    image: "/bamboo-toothbrush-biodegradable-dental-care.jpg",
    seller: "EcoDental",
    rating: 4.9,
    reviews: 312,
    isVerified: true,
  },
  {
    id: "17",
    title: "Organic Shampoo Bar",
    description: "Zero-waste shampoo bar with natural ingredients",
    price: 649,
    category: "Beauty & Personal Care",
    image: "/organic-shampoo-bar-zero-waste-natural.jpg",
    seller: "Pure Beauty",
    rating: 4.7,
    reviews: 187,
    isVerified: true,
  },
  {
    id: "18",
    title: "Natural Deodorant Set",
    description: "Aluminum-free deodorant made with organic ingredients",
    price: 1199,
    category: "Beauty & Personal Care",
    image: "/natural-deodorant-aluminum-free-organic.jpg",
    seller: "Clean Living",
    rating: 4.5,
    reviews: 156,
    isVerified: true,
  },
  // Additional Sports & Outdoors products
  {
    id: "19",
    title: "Stainless Steel Water Bottle",
    description: "Insulated water bottle for outdoor adventures",
    price: 2299,
    category: "Sports & Outdoors",
    image: "/stainless-steel-water-bottle-insulated-outdoor.jpg",
    seller: "Adventure Gear",
    rating: 4.8,
    reviews: 234,
    isVerified: true,
  },
  {
    id: "20",
    title: "Eco-Friendly Camping Gear",
    description: "Sustainable camping set with biodegradable soap and utensils",
    price: 3899,
    category: "Sports & Outdoors",
    image: "/eco-friendly-camping-gear-set-with-biodegradable-s.jpg",
    seller: "Green Adventures",
    rating: 4.6,
    reviews: 98,
    isVerified: true,
  },
  {
    id: "21",
    title: "Cork Yoga Blocks",
    description: "Natural cork yoga blocks for better alignment and support",
    price: 1799,
    category: "Sports & Outdoors",
    image: "/natural-cork-yoga-blocks-for-alignment-and-support.jpg",
    seller: "Mindful Movement",
    rating: 4.7,
    reviews: 145,
    isVerified: true,
  },
]

export function ProductGrid() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {products.map((product) => (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  )
}
